@startuml

title __DAO's Class Diagram__\n

  namespace org.stroganov {
    namespace dao {
      class org.stroganov.dao.DAOFactory {
          {static} - ERROR_PARAMETER_MESSAGE : String
          {static} - REALIZATION_EXCEPTION_MESSAGE : String
          {static} + getLibraryDAO()
      }
    }
  }
  

  namespace org.stroganov {
    namespace dao {
      enum DAOType {
        H2DATABASE
        JSON
      }
    }
  }
  

  namespace org.stroganov {
    namespace dao {
      class org.stroganov.dao.JsonDataSource {
          ~ bookList : List<Book>
          ~ userList : List<User>
          {static} - instance : JsonDataSource
          + addBook()
          + addBookList()
          + blockUser()
          + deleteBook()
          + deleteUser()
          + findBook()
          + findUser()
          {static} + getInstance()
          + saveUser()
          + unblockUser()
          - JsonDataSource()
      }
    }
  }
  

  namespace org.stroganov {
    namespace dao {
      interface org.stroganov.dao.LibraryDAO {
          {abstract} + addBook()
          {abstract} + addBookList()
          {abstract} + blockUser()
          {abstract} + deleteBook()
          {abstract} + deleteUser()
          {abstract} + findBook()
          {abstract} + findUser()
          {abstract} + saveUser()
          {abstract} + unblockUser()
      }
    }
  }
  

  org.stroganov.dao.JsonDataSource .up.|> org.stroganov.dao.LibraryDAO
  org.stroganov.dao.JsonDataSource o-- org.stroganov.JsonDBAPI.JsonDBLoader : jsonDBLoader


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
