@startuml

title __JSONDBAPI's Class Diagram__\n

  namespace org.stroganov {
    namespace JsonDBAPI {
      class org.stroganov.JsonDBAPI.BookBuilder {
          - currentJsonObject : JsonObject
          + BookBuilder()
          + buildBook()
      }
    }
  }
  

  namespace org.stroganov {
    namespace JsonDBAPI {
      class org.stroganov.JsonDBAPI.JsonDBLoader {
          {static} + DB_EXCEPTIONS : String
          - logger : Logger
          - properties : Properties
          + JsonDBLoader()
          + loadAuthors()
          + loadBookMarks()
          + loadBooks()
          + loadUsers()
      }
    }
  }
  

  namespace org.stroganov {
    namespace JsonDBAPI {
      class org.stroganov.JsonDBAPI.JsonDBSaver {
          - properties : Properties
          + JsonDBSaver()
          + saveEntityListToJsonFormatFile()
      }
    }
  }
  

  namespace org.stroganov {
    namespace JsonDBAPI {
      class org.stroganov.JsonDBAPI.JsonParser {
          + getBookFromJsonElement()
          + getListAuthorsFromDB()
          + getListBookMarkFromDB()
          + getListBooksFromDB()
          + getListUsersFromDB()
          + getUserFromJsonElement()
      }
    }
  }
  

  namespace org.stroganov {
    namespace JsonDBAPI {
      class org.stroganov.JsonDBAPI.JsonSerializer {
          {static} + entitySerializer()
      }
    }
  }
  

  namespace org.stroganov {
    namespace JsonDBAPI {
      class org.stroganov.JsonDBAPI.UserBuilder {
          - currentJsonObject : JsonObject
          + UserBuilder()
          + buildUser()
      }
    }
  }
  

  org.stroganov.JsonDBAPI.JsonDBLoader o-- org.stroganov.JsonDBAPI.JsonParser : jsonParser


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
