package org.stroganov.wsClient;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import org.stroganov.entities.User;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "AdminService", targetNamespace = "http://ws.stroganov.org/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
        ObjectFactory.class
})
public interface AdminServiceClient {


    /**
     * @param arg0
     * @return returns boolean
     * @throws org.stroganov.wsClient.IOException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.stroganov.org/AdminService/addUserRequest", output = "http://ws.stroganov.org/AdminService/addUserResponse", fault = {
            @FaultAction(className = IOException_Exception.class, value = "http://ws.stroganov.org/AdminService/addUser/Fault/IOException")
    })
    public boolean addUser(
            @WebParam(name = "arg0", partName = "arg0")
                    User arg0)
            throws IOException_Exception
    ;

    /**
     * @param arg0
     * @return returns boolean
     * @throws org.stroganov.wsClient.IOException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.stroganov.org/AdminService/deleteUserRequest", output = "http://ws.stroganov.org/AdminService/deleteUserResponse", fault = {
            @FaultAction(className = IOException_Exception.class, value = "http://ws.stroganov.org/AdminService/deleteUser/Fault/IOException")
    })
    public boolean deleteUser(
            @WebParam(name = "arg0", partName = "arg0")
                    User arg0)
            throws IOException_Exception
    ;

    /**
     * @param arg0
     * @return returns boolean
     * @throws org.stroganov.wsClient.IOException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.stroganov.org/AdminService/blockUserRequest", output = "http://ws.stroganov.org/AdminService/blockUserResponse", fault = {
            @FaultAction(className = IOException_Exception.class, value = "http://ws.stroganov.org/AdminService/blockUser/Fault/IOException")
    })
    public boolean blockUser(
            @WebParam(name = "arg0", partName = "arg0")
                    User arg0)
            throws IOException_Exception
    ;

    /**
     * @param arg0
     * @return returns boolean
     * @throws org.stroganov.wsClient.IOException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.stroganov.org/AdminService/unblockUserRequest", output = "http://ws.stroganov.org/AdminService/unblockUserResponse", fault = {
            @FaultAction(className = IOException_Exception.class, value = "http://ws.stroganov.org/AdminService/unblockUser/Fault/IOException")
    })
    public boolean unblockUser(
            @WebParam(name = "arg0", partName = "arg0")
                    User arg0)
            throws IOException_Exception
    ;

    /**
     * @return returns org.stroganov.ws.HistoryArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.stroganov.org/AdminService/getAllHistoryRequest", output = "http://ws.stroganov.org/AdminService/getAllHistoryResponse")
    public HistoryArray getAllHistory();
}
