package org.stroganov.wsClient;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import org.stroganov.entities.*;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "LibraryService", targetNamespace = "http://ws.stroganov.org/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
        ObjectFactory.class
})
public interface LibraryService {


    /**
     * @param arg0
     * @return returns org.stroganov.ws.BookArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.stroganov.org/LibraryService/findBooksWithUserBookMarksRequest", output = "http://ws.stroganov.org/LibraryService/findBooksWithUserBookMarksResponse")
    public BookArray findBooksWithUserBookMarks(
            @WebParam(name = "arg0", partName = "arg0")
                    User arg0);

    /**
     * @param arg0
     * @return returns org.stroganov.ws.User
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.stroganov.org/LibraryService/findUserRequest", output = "http://ws.stroganov.org/LibraryService/findUserResponse")
    public User findUser(
            @WebParam(name = "arg0", partName = "arg0")
                    String arg0);

    /**
     * @param arg1
     * @param arg0
     * @return returns org.stroganov.ws.BookArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.stroganov.org/LibraryService/findBooksByYearsRangeRequest", output = "http://ws.stroganov.org/LibraryService/findBooksByYearsRangeResponse")
    public BookArray findBooksByYearsRange(
            @WebParam(name = "arg0", partName = "arg0")
                    int arg0,
            @WebParam(name = "arg1", partName = "arg1")
                    int arg1);

    /**
     * @param arg0
     * @return returns boolean
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.stroganov.org/LibraryService/deleteAuthorWithAllHisBooksRequest", output = "http://ws.stroganov.org/LibraryService/deleteAuthorWithAllHisBooksResponse", fault = {
            @FaultAction(className = IOException_Exception.class, value = "http://ws.stroganov.org/LibraryService/deleteAuthorWithAllHisBooks/Fault/IOException")
    })
    public boolean deleteAuthorWithAllHisBooks(
            @WebParam(name = "arg0", partName = "arg0")
                    Author arg0)
            throws IOException_Exception
    ;

    /**
     * @param arg0
     * @return returns org.stroganov.ws.BookArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.stroganov.org/LibraryService/findBooksByPartAuthorNameRequest", output = "http://ws.stroganov.org/LibraryService/findBooksByPartAuthorNameResponse")
    public BookArray findBooksByPartAuthorName(
            @WebParam(name = "arg0", partName = "arg0")
                    String arg0);

    /**
     * @param arg0
     * @return returns org.stroganov.ws.BookArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.stroganov.org/LibraryService/findBookByPartNameRequest", output = "http://ws.stroganov.org/LibraryService/findBookByPartNameResponse")
    public BookArray findBookByPartName(
            @WebParam(name = "arg0", partName = "arg0")
                    String arg0);

    /**
     * @param arg2
     * @param arg1
     * @param arg0
     * @return returns org.stroganov.ws.BookArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.stroganov.org/LibraryService/findBooksByParametersRequest", output = "http://ws.stroganov.org/LibraryService/findBooksByParametersResponse")
    public BookArray findBooksByParameters(
            @WebParam(name = "arg0", partName = "arg0")
                    int arg0,
            @WebParam(name = "arg1", partName = "arg1")
                    int arg1,
            @WebParam(name = "arg2", partName = "arg2")
                    String arg2);

    /**
     * @param userName
     * @return returns org.stroganov.ws.UserArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.stroganov.org/LibraryService/getNewUserRequest", output = "http://ws.stroganov.org/LibraryService/getNewUserResponse")
    public UserArray getNewUser(
            @WebParam(name = "userName", partName = "userName")
                    String userName);

    /**
     * @param arg0
     * @return returns boolean
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.stroganov.org/LibraryService/addBookRequest", output = "http://ws.stroganov.org/LibraryService/addBookResponse", fault = {
            @FaultAction(className = IOException_Exception.class, value = "http://ws.stroganov.org/LibraryService/addBook/Fault/IOException")
    })
    public boolean addBook(
            @WebParam(name = "arg0", partName = "arg0")
                    Book arg0)
            throws IOException_Exception
    ;

    /**
     * @param arg0
     * @return returns boolean
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.stroganov.org/LibraryService/addBookLIstRequest", output = "http://ws.stroganov.org/LibraryService/addBookLIstResponse", fault = {
            @FaultAction(className = IOException_Exception.class, value = "http://ws.stroganov.org/LibraryService/addBookLIst/Fault/IOException")
    })
    public boolean addBookLIst(
            @WebParam(name = "arg0", partName = "arg0")
                    BookArray arg0)
            throws IOException_Exception
    ;

    /**
     * @param arg0
     * @return returns boolean
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.stroganov.org/LibraryService/deleteBookRequest", output = "http://ws.stroganov.org/LibraryService/deleteBookResponse", fault = {
            @FaultAction(className = IOException_Exception.class, value = "http://ws.stroganov.org/LibraryService/deleteBook/Fault/IOException")
    })
    public boolean deleteBook(
            @WebParam(name = "arg0", partName = "arg0")
                    Book arg0)
            throws IOException_Exception
    ;

    /**
     * @param arg0
     * @return returns org.stroganov.ws.Book
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.stroganov.org/LibraryService/findBookRequest", output = "http://ws.stroganov.org/LibraryService/findBookResponse")
    public Book findBook(
            @WebParam(name = "arg0", partName = "arg0")
                    String arg0);

    /**
     * @param arg0
     * @return returns boolean
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.stroganov.org/LibraryService/addUserRequest", output = "http://ws.stroganov.org/LibraryService/addUserResponse", fault = {
            @FaultAction(className = IOException_Exception.class, value = "http://ws.stroganov.org/LibraryService/addUser/Fault/IOException")
    })
    public boolean addUser(
            @WebParam(name = "arg0", partName = "arg0")
                    User arg0)
            throws IOException_Exception
    ;

    /**
     * @param arg0
     * @return returns boolean
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.stroganov.org/LibraryService/deleteUserRequest", output = "http://ws.stroganov.org/LibraryService/deleteUserResponse", fault = {
            @FaultAction(className = IOException_Exception.class, value = "http://ws.stroganov.org/LibraryService/deleteUser/Fault/IOException")
    })
    public boolean deleteUser(
            @WebParam(name = "arg0", partName = "arg0")
                    User arg0)
            throws IOException_Exception
    ;

    /**
     * @param arg0
     * @return returns boolean
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.stroganov.org/LibraryService/blockUserRequest", output = "http://ws.stroganov.org/LibraryService/blockUserResponse", fault = {
            @FaultAction(className = IOException_Exception.class, value = "http://ws.stroganov.org/LibraryService/blockUser/Fault/IOException")
    })
    public boolean blockUser(
            @WebParam(name = "arg0", partName = "arg0")
                    User arg0)
            throws IOException_Exception
    ;

    /**
     * @param arg0
     * @return returns boolean
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.stroganov.org/LibraryService/unblockUserRequest", output = "http://ws.stroganov.org/LibraryService/unblockUserResponse", fault = {
            @FaultAction(className = IOException_Exception.class, value = "http://ws.stroganov.org/LibraryService/unblockUser/Fault/IOException")
    })
    public boolean unblockUser(
            @WebParam(name = "arg0", partName = "arg0")
                    User arg0)
            throws IOException_Exception
    ;

    /**
     * @param arg0
     * @return returns boolean
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.stroganov.org/LibraryService/addBookMarkRequest", output = "http://ws.stroganov.org/LibraryService/addBookMarkResponse", fault = {
            @FaultAction(className = IOException_Exception.class, value = "http://ws.stroganov.org/LibraryService/addBookMark/Fault/IOException")
    })
    public boolean addBookMark(
            @WebParam(name = "arg0", partName = "arg0")
                    BookMark arg0)
            throws IOException_Exception
    ;

    /**
     * @param arg0
     * @return returns boolean
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.stroganov.org/LibraryService/deleteBookMarkRequest", output = "http://ws.stroganov.org/LibraryService/deleteBookMarkResponse", fault = {
            @FaultAction(className = IOException_Exception.class, value = "http://ws.stroganov.org/LibraryService/deleteBookMark/Fault/IOException")
    })
    public boolean deleteBookMark(
            @WebParam(name = "arg0", partName = "arg0")
                    BookMark arg0)
            throws IOException_Exception
    ;

    /**
     * @param arg0
     * @return returns boolean
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.stroganov.org/LibraryService/addAuthorRequest", output = "http://ws.stroganov.org/LibraryService/addAuthorResponse", fault = {
            @FaultAction(className = IOException_Exception.class, value = "http://ws.stroganov.org/LibraryService/addAuthor/Fault/IOException")
    })
    public boolean addAuthor(
            @WebParam(name = "arg0", partName = "arg0")
                    Author arg0)
            throws IOException_Exception
    ;

    /**
     * @param arg0
     * @return returns org.stroganov.ws.Author
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.stroganov.org/LibraryService/findAuthorRequest", output = "http://ws.stroganov.org/LibraryService/findAuthorResponse")
    public Author findAuthor(
            @WebParam(name = "arg0", partName = "arg0")
                    String arg0);

    /**
     * @param arg0
     * @return returns org.stroganov.ws.BookMarkArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.stroganov.org/LibraryService/findUserBookMarksRequest", output = "http://ws.stroganov.org/LibraryService/findUserBookMarksResponse")
    public BookMarkArray findUserBookMarks(
            @WebParam(name = "arg0", partName = "arg0")
                    User arg0);

    /**
     * @param arg0
     * @return returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.stroganov.org/LibraryService/addHistoryEventRequest", output = "http://ws.stroganov.org/LibraryService/addHistoryEventResponse")
    public boolean addHistoryEvent(
            @WebParam(name = "arg0", partName = "arg0")
                    History arg0);

    /**
     * @return returns org.stroganov.ws.HistoryArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.stroganov.org/LibraryService/getAllHistoryRequest", output = "http://ws.stroganov.org/LibraryService/getAllHistoryResponse")
    public HistoryArray getAllHistory();

}
