
package org.stroganov.wsClient;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import org.stroganov.entities.Author;
import org.stroganov.entities.BookMark;
import org.stroganov.entities.History;

import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "UserService", targetNamespace = "http://ws.stroganov.org/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
        ObjectFactory.class
})
public interface UserServiceClient {


    /**
     * @param arg0
     * @return returns boolean
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.stroganov.org/UserService/addBookMarkRequest", output = "http://ws.stroganov.org/UserService/addBookMarkResponse", fault = {
            @FaultAction(className = IOException_Exception.class, value = "http://ws.stroganov.org/UserService/addBookMark/Fault/IOException")
    })
    public boolean addBookMark(
            @WebParam(name = "arg0", partName = "arg0")
                    BookMark arg0)
            throws IOException_Exception
    ;

    /**
     * @param arg0
     * @return returns boolean
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.stroganov.org/UserService/deleteBookMarkRequest", output = "http://ws.stroganov.org/UserService/deleteBookMarkResponse", fault = {
            @FaultAction(className = IOException_Exception.class, value = "http://ws.stroganov.org/UserService/deleteBookMark/Fault/IOException")
    })
    public boolean deleteBookMark(
            @WebParam(name = "arg0", partName = "arg0")
                    BookMark arg0)
            throws IOException_Exception
    ;

    /**
     * @param arg0
     * @return returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.stroganov.org/UserService/addHistoryEventRequest", output = "http://ws.stroganov.org/UserService/addHistoryEventResponse")
    public boolean addHistoryEvent(
            @WebParam(name = "arg0", partName = "arg0")
                    History arg0);

    /**
     * @param arg0
     * @return returns boolean
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.stroganov.org/UserService/deleteAuthorWithAllHisBooksRequest", output = "http://ws.stroganov.org/UserService/deleteAuthorWithAllHisBooksResponse", fault = {
            @FaultAction(className = IOException_Exception.class, value = "http://ws.stroganov.org/UserService/deleteAuthorWithAllHisBooks/Fault/IOException")
    })
    public boolean deleteAuthorWithAllHisBooks(
            @WebParam(name = "arg0", partName = "arg0")
                    Author arg0)
            throws IOException_Exception
    ;

}
